# Generated by Django 3.0.4 on 2020-04-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='inpuiry',
            new_name='article',
        ),
    ]
