# Generated by Django 3.0.4 on 2020-04-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_auto_20200411_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='inquiry',
        ),
    ]
