# Generated by Django 3.0.4 on 2020-04-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
    ]
